### PR TITLE
Add Python 2.7 and Travis CI

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
See https://travis-ci.org/jayvdb/python-srcinfo/builds/597189157 for green builds.

**Comment by kyrias** [comment]
Hey, thanks for the PR!

I'm not going to add support for Python 2, both because I don't care about adding support for older versions without any real reason, and because it goes EOL in less than 3 months.

Running the test suite under Travis is a great idea though, so if you remove the py2.7 stuff I'll merge this.

**Comment by polyzen** [comment]
Please also use caching: https://docs.travis-ci.com/user/caching/#pip-cache

**Comment by jayvdb** [comment]
I've added a Python 3 only .travis at https://github.com/kyrias/python-srcinfo/pull/11.

If you dont mind, I'll also rebase this and merge together the Python 2 stuff into a single commit, and then this PR can be closed if you dont want to carry around Python 2 support for a few months until the EOL.  I need the patch to submit as part of https://build.opensuse.org/package/show/home:jayvdb:py-new/python-srcinfo, in order to improve openSUSE build system's support of Arch.

**Comment by jayvdb** [comment]
https://travis-ci.org/jayvdb/python-srcinfo/jobs/597464186 was with Python 2 added to Travis.

I've removed the Travis bits, so that the patch is smaller and easier to revert, if you did want to merge it and back it out it in a few months.

**Comment by kyrias** [comment]
While that sounds interesting and all, if you need Python 2.7 support for it you'll have to keep your own fork with those changes.  I really have no intention of adding any legacy code to any of my projects.

Additionally, that's a dead link.

**Comment by jayvdb** [comment]
Ya, sorry, it is a dead link as the packaging request was accepted https://build.opensuse.org/request/show/738137
So it is now at https://build.opensuse.org/package/show/devel:languages:python/python-srcinfo
Yes, I'll do any patching needed to keep Python 2 alive, or kill it if the team here introduces changes which makes that too difficult.

**Pull request closed without merging**
