### PR TITLE
[RFC] Allow empty values

### PR DESCRIPTION
**Pull request by falconindy**

### CODE REVIEW

**Comment by Morganamilo** [comment]
The parser already allows empty values due to:
https://github.com/kyrias/python-srcinfo/blob/8e60f3caf49125231f26ae9bdf68959539015994/srcinfo/parse.py#L92-L93

Although there's a slight catch. The parsee only accepts empty values if they are formatted like so `"depends = "`. Note the trailing space after the = , if the space is not there then the parser fails. Luckily makepkg puts in the tailing space when it generates srcinfos like this.

Now that there are patches for makepkg to fix this, would it be better to disallow these values after the next pacman release?

Anyway as it stands now this wouldn't change anything, but looking at the diffs you changed quite a bit of the parsing logic which seem to improve white space handling in general. So This is a good pr but for different reasons than the tittle.

**Comment by falconindy** [comment]
Not sure I follow. I'm talking about allowing empty values, but the line of code you're quoting seems to be meant to skip empty lines, commented lines, or unparseable lines.

If you revert the code I changed in parse.py, you'll see that the test I added fails. This is what I'm trying to allow.

**Comment by falconindy** [comment]
Because the empty attribute in package section should be able to override the attribute from the global section. You're right that there's cases where makepkg *incorrectly* emits empty attributes, but makepkg also *intentionally* (and correctly) emits an empty value for something like `depends=()` inside `package_foo()`.

**Comment by falconindy** [comment]
And I see now that my patch doesn't actually quite do this...

**Comment by Morganamilo** [comment]
>makepkg also intentionally (and correctly) emits an empty value for something like depends=() inside package_foo().

I never thought about this, thanks for pointing it out.

**Comment by kyrias** [comment]
Thanks!

**Pull request merged**
