### PR TITLE
MANIFEST.in: Add tests to sdist

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by kyrias** [comment]
Good catch.  Though since setuptools by default includes anything named `test/test*.py`, we might just want to add `test/__init__.py` explicitly?

**Comment by jayvdb** [comment]
Explicit is better than implicit.

**Comment by kyrias** [comment]
Sure, but by that reasoning you should also add everything else that is documented as being added automatically.  (`srcinfo/` itself and `setup.py`.)  Now I hope you agree that adding those would be silly, so why would it be any different with `test/`?

**Comment by jayvdb** [comment]
This is the standard rule added by `check-manifest` for non-source sub-directories.  It isn't a superfluous entry like those you are rightly calling silly.  It is one line.  One line is necessary: either this like, or the one you propose.

Using the recursive rule instead of `test/__init__.py` allows for the creation of subdirectories in the future.  It is a broader rule.

If you want me to change it to `test/__init__.py`, I'll be happy to oblige.

**Comment by kyrias** [comment]
Fair enough, thanks!

**Pull request merged**
